export const UNCHECKED = "UNCHECKED";
export const ABSENT = "ABSENT";
export const WRONG_PLACE = "WRONG_PLACE";
export const CORRECT = "CORRECT";

export const STATUSES = {
  UNCHECKED: UNCHECKED,
  ABSENT: ABSENT,
  WRONG_PLACE: WRONG_PLACE,
  CORRECT: CORRECT
};
